Enuser pip

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -25,7 +25,12 @@ jobs:
       - name: Set up venv
         run: python -m venv venv
       - name: Upgrade pip in venv
-        run: venv\Scripts\python -m pip install --upgrade pip
+        run:
+	  venv\Scripts\python -m ensurepip --upgrade || (
+          echo "ensurepip failed, installing pip manually" &&
+          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&
+          venv\Scripts\python get-pip.py
+      )
       - name: Install dependencies in venv
         run: venv\Scripts\pip install --no-user -r docker/requirements.txt
       - name: Run tests
